FROM node:18 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . ./
RUN npm run build

FROM node:18
ARG API_PORT=5000 \
    NODE_NAME='' \
    GCP_AUTH_JSON=''\
    GPT_TOKEN=''
ENV API_PORT=${API_PORT} \
    NODE_NAME=${NODE_NAME} \
    GCP_AUTH_JSON=${GCP_AUTH_JSON} \
    GPT_TOKEN=''
WORKDIR /app
COPY --from=build /app/build /app/package.json /app/package-lock.json ./
COPY --from=build /app/node_modules ./node_modules
EXPOSE  ${API_PORT}
CMD ["npm","run","prod"]