### GPT completion
POST https://api.openai.com/v1/chat/completions
Content-Type: application/json
Authorization: Bearer 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

{
    "messages": [
        {
            "role": "system",
            "content": "I want you to answer user prompts with json format using name, lastname and age attributes"
        }
    ],
    "model": "text-davinci-003"
}
