---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace}}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.api.host}}`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: {{ .Values.name}}
      port: {{ .Values.api.exposedPort}}
  tls:
    secretName:  {{ .Values.ingress.tls.SecretName}}
