apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: { { .Values.name } }
  namespace: { { .Values.namespace } }
spec:
  minAvailable: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { .Values.name } }
