kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name}}
  namespace: {{ .Values.namespace}}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name}}
  ports:
  - protocol: TCP
    name: {{ .Values.name}}
    port: {{ .Values.http.exposedPort}}
    targetPort: {{ .Values.http.exposedPort}}