name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders-f
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders-f
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/greedhub/ciu-1er-parcial-frontend:latest
          context: "{{defaultContext}}:primer-parcial/frontend"
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy_frontend:
    runs-on: self-hosted
    needs: build_frontend
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Helm
        uses: azure/setup-helm@v3
        id: install
      - name: "Apply Kubeconfig"
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: "Deploy with Helm"
        run: |
          cd ./primer-parcial/frontend/helm-chart && \
          export TIMESTAMP=$(date +%s) && \
          helm upgrade -i --force -n default 1er-p-frontend -f values.yaml \
          --set-string timestamp=$TIMESTAMP \
          ./

  build_backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders-b
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders-b
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/greedhub/ciu-1er-parcial-backend:latest
          context: "{{defaultContext}}:primer-parcial/backend"
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Install credentials
        run: echo ${{ secrets.GPT_TOKEN }} > ./primer-parcial/backend/credentials/gcp.json

  deploy_backend:
    runs-on: self-hosted
    needs: build_backend
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Helm
        uses: azure/setup-helm@v3
        id: install
      - name: "Apply Kubeconfig"
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: "Deploy with Helm"
        run: |
          cd ./primer-parcial/backend/helm-chart && \
          export TIMESTAMP=$(date +%s) && \
          helm upgrade -i --force -n default 1er-p-backend -f values.yaml \
          --set-string timestamp=$TIMESTAMP \
          --set-string gptToken=${{ secrets.GPT_TOKEN }} \
          ./
